<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title> • foehnix</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet">
<script src="../extra.js"></script><meta property="og:title" content="">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">foehnix</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.4</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/foehnix.html">Getting started</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Demos
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/ellboegen.html">Ellbögen (Tyrol, A)</a>
    </li>
    <li>
      <a href="../articles/viejas.html">Viejas (California, USA)</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/foehnix.html">Foehnix Demo</a>
    </li>
    <li>
      <a href="../articles/windrose.html">[Plot] Wind Rose</a>
    </li>
    <li>
      <a href="../articles/tsplot.html">[Plot] Time Series</a>
    </li>
    <li>
      <a href="../articles/image.html">[Plot] Hovmöller Diagram</a>
    </li>
    <li>
      <a href="../articles/simulation.html">Simulation Examples</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Advanced
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/mixedmodel.html">Statistical Model</a>
    </li>
    <li>
      <a href="../articles/logisticregression.html">Logistic Regression (IWLS)</a>
    </li>
    <li>
      <a href="../articles/inference.html">Inference</a>
    </li>
    <li>
      <a href="../articles/advanced_simulation.html">Censoring and Truncation</a>
    </li>
    <li>
      <a href="../articles/families.html">foehnix Families</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/retostauffer/Rfoehnix">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><script src="ellboegen_files/htmlwidgets-1.3/htmlwidgets.js"></script><script src="ellboegen_files/jquery-1.12.4/jquery.min.js"></script><link href="ellboegen_files/leaflet-1.3.1/leaflet.css" rel="stylesheet">
<script src="ellboegen_files/leaflet-1.3.1/leaflet.js"></script><link href="ellboegen_files/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">
<script src="ellboegen_files/Proj4Leaflet-1.0.1/proj4-compressed.js"></script><script src="ellboegen_files/Proj4Leaflet-1.0.1/proj4leaflet.js"></script><link href="ellboegen_files/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">
<script src="ellboegen_files/leaflet-binding-2.0.2/leaflet.js"></script><script src="ellboegen_files/leaflet-providers-1.1.17/leaflet-providers.js"></script><script src="ellboegen_files/leaflet-providers-plugin-2.0.2/leaflet-providers-plugin.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1></h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/retostauffer/Rfoehnix/blob/master/vignettes/ellboegen.Rmd"><code>vignettes/ellboegen.Rmd</code></a></small>
      <div class="hidden name"><code>ellboegen.Rmd</code></div>

    </div>

    
    
<div id="data-set-description" class="section level1">
<h1 class="hasAnchor">
<a href="#data-set-description" class="anchor"></a>Data Set Description</h1>
<p>The “Tyrolean” data set provides hourly observations from two stations, namely “Ellbögen” and “Sattelberg” located in Tyrol, Austria.</p>
<p>Ellbögen is our target station (valley site) located in the Wipp Valley, a north-south oriented alpine valley on the northern side of the European Alps. To the north the Wipp Valley opens into the Inn Valley (close to Innsbruck, the capitol of Tyrol), to the south the valley ends at a narrow gap in the main Alpine ridge called Brennerpass (<span class="math inline">\(1370~m\)</span>; the pass between Austria and Italy) flanked by mountains (<span class="math inline">\(&gt;2100~m\)</span>). The Wipp Valley is one of the lowest and most distinct cuts trough the Alpine mountain range and well known for south foehn (north of the Alps). Station Sattelberg serves as crest station and provides observations of the upstream air mass during south foehn events. The station is located on top of the mountain to the west of the pass.</p>
<div id="htmlwidget-7f7b9405ceb7292bc89c" style="width:100%;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-7f7b9405ceb7292bc89c">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"http://openstreetmap.org\">OpenStreetMap<\/a> contributors, <a href=\"http://creativecommons.org/licenses/by-sa/2.0/\">CC-BY-SA<\/a>"}]},{"method":"addPopups","args":[47.18694,11.42889,"Station Ellbögen, 1080 m a.m.s.l.",null,null,{"maxWidth":300,"minWidth":50,"autoPan":true,"keepInView":false,"closeButton":true,"className":""}]},{"method":"addPopups","args":[47.01083,11.47889,"Station Sattelberg, 2107 m a.m.s.l.",null,null,{"maxWidth":300,"minWidth":50,"autoPan":true,"keepInView":false,"closeButton":true,"className":""}]},{"method":"addProviderTiles","args":["OpenTopoMap",null,null,{"errorTileUrl":"","noWrap":false,"detectRetina":false}]}],"setView":[[47.098885,11.45389],10.5,[]],"limits":{"lat":[47.01083,47.18694],"lng":[11.42889,11.47889]}},"evals":[],"jsHooks":[]}</script>
</div>
<div id="loading-the-data-set" class="section level1">
<h1 class="hasAnchor">
<a href="#loading-the-data-set" class="anchor"></a>Loading the Data Set</h1>
<p>The call <a href="references/demodata"><code><a href="../reference/demodata.html">demodata("tyrol")</a></code></a> returns the combined data set for both station (Ellbögen and Sattelberg). In addition, the potential temperature difference between the two stations is calculated by reducing the dry air temperature from “Sattelberg” to the height of “Ellbögen” (dry adiabatic lapse rate of 1K per 100m; stored on <code>diff_t</code>). Details can be found on the <a href="references/demodata.html"><code>demodata</code></a> reference page.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data &lt;-<span class="st"> </span><span class="kw"><a href="../reference/demodata.html">demodata</a></span>(<span class="st">"tyrol"</span>)
<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(data, <span class="dt">n =</span> <span class="dv">3</span>)</code></pre></div>
<pre><code>##                      dd  ff  rh    t crest_dd crest_ff crest_rh crest_t
## 2006-01-01 01:00:00 171 0.6  90 -0.4      180     10.8      100    -7.8
## 2006-01-01 02:00:00 268 0.3 100 -1.8      186     12.5      100    -8.0
## 2006-01-01 03:00:00 115 5.2  79  0.9      181     11.3      100    -7.4
##                     diff_t
## 2006-01-01 01:00:00   2.87
## 2006-01-01 02:00:00   4.07
## 2006-01-01 03:00:00   1.97</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Check if our object is a numeric zoo object:</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"is.zoo"</span> =<span class="st"> </span><span class="kw">is.zoo</span>(data),
  <span class="st">"is.numeric"</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/numeric">is.numeric</a></span>(data),
  <span class="st">"is regular"</span> =<span class="st"> </span><span class="kw">is.regular</span>(data),
  <span class="st">"is strictly regular"</span> =<span class="st"> </span><span class="kw">is.regular</span>(data, <span class="dt">strict =</span> <span class="ot">TRUE</span>))</code></pre></div>
<pre><code>##              is.zoo          is.numeric          is regular 
##                TRUE                TRUE                TRUE 
## is strictly regular 
##               FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"tepmoral resolution (seconds)"</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/time">deltat</a></span>(data),
  <span class="st">"missing values"</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(data)))</code></pre></div>
<pre><code>## tepmoral resolution (seconds)                missing values 
##                          3600                         87267</code></pre>
<p>The data set returned is a regular <code>numeric</code> <code>zoo</code> time series object. Note that the data set is not strictly regular (contains hourly observations, but some are missing) and contains quite some missing values (<code>NA</code>). This is not a problem as the functions and methods will take care of missing values and inflate the time series object (regular <span class="math inline">\(\rightarrow\)</span> strictly regular).</p>
<p><strong>Important:</strong> The names of the variables in the Tyrolean data set are the “<em>standard names</em>” on which most functions and methods provided by this package are based on. To be precise:</p>
<ul>
<li>
<strong>Valley station:</strong> air temperature <code>t</code>, relative humidity <code>rh</code>, wind speed <code>ff</code>, wind direction <code>dd</code> (meteorological, degrees <span class="math inline">\(\in [0, 360]\)</span>)</li>
<li>
<strong>Crest station:</strong> air temperature <code>crest_t</code>, relative humidity <code>crest_rh</code>, wind speed <code>crest_ff</code>, wind direction <code>crest_dd</code> (<span class="math inline">\(\in [0, 360]\)</span>)</li>
<li>
<strong>In addition:</strong> Potential temperature difference <code>diff_t</code> (calculated by <a href="references/demodata.html"><code>demodata</code></a>
</li>
</ul>
<p>… however, all functions arguments which allow to set custom names (see “<a href="articles/viejas.html">Demos &gt; Viejas (California, USA)</a>” or function references).</p>
<p>After preparing the data set (regular or strictly regular <code>zoo   object with</code>numeric` values) we can investigate the observed wind information.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/par">par</a></span>(<span class="dt">mfrow =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span>,<span class="dv">2</span>))
<span class="co"># Observed wind speed/wind direction "Ellboegen"</span>
<span class="co"># Expects a variable 'dd' and 'ff' by default. Thus,</span>
<span class="co"># 'ddvar'/'ffvar' do not have to be specified.</span>
<span class="kw"><a href="../reference/windrose.html">windrose</a></span>(data,
         <span class="dt">main =</span> <span class="st">"Windrose Ellbögen"</span>,
         <span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, <span class="dv">35</span>, <span class="dt">by =</span> <span class="dv">5</span>))
<span class="co"># Observed wind speed/wind direction "Sattelberg"</span>
<span class="co"># Specify dd/ff of the crest station (ddvar, ffvar)</span>
<span class="kw"><a href="../reference/windrose.html">windrose</a></span>(data, <span class="dt">ddvar =</span> <span class="st">"crest_dd"</span>, <span class="dt">ffvar =</span> <span class="st">"crest_ff"</span>,
         <span class="dt">main =</span> <span class="st">"Windrose Sattelberg"</span>, <span class="dt">hue =</span> <span class="dv">270</span>,
         <span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, <span class="dv">35</span>, <span class="dt">by =</span> <span class="dv">5</span>))</code></pre></div>
<p><img src="ellboegen_files/figure-html/emp_windrose-1.png" width="1152"></p>
<p>Based on prior knowledge and the plots above we define two “foehn wind sectors” as follows:</p>
<ul>
<li>At <strong>Ellbögen</strong> the observed wind direction (<code>dd</code>) needs to be along valley within 43 and 223 degrees (south-easterly; a 180 degree sector).</li>
<li>At <strong>Sattelberg</strong> the observed wind direction (<code>crest_dd</code>) needs to be within 90 and 270 degrees (south wind; 180 degree sector).</li>
</ul>
<p>The wind sector(s) can be added to the <a href="references/windrose.html"><code>windrose</code></a> plots for visual justification, but well also be used later when estimating the <a href="references/foehnix.html"><code>foehnix</code></a> classification model.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/par">par</a></span>(<span class="dt">mfrow =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">1</span>,<span class="dv">2</span>))
<span class="co"># Ellboegen with custom wind sector</span>
<span class="kw"><a href="../reference/windrose.html">windrose</a></span>(data,
         <span class="dt">windsector =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="st">"south-east wind"</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">43</span>, <span class="dv">223</span>)),
         <span class="dt">main =</span> <span class="st">"Windrose Ellbögen"</span>,
         <span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, <span class="dv">35</span>, <span class="dt">by =</span> <span class="dv">5</span>))
<span class="co"># Observed wind speed/wind direction "Sattelberg"</span>
<span class="co"># Specify custom variable names for dd/ff (crest_dd, crest_ff).</span>
<span class="kw"><a href="../reference/windrose.html">windrose</a></span>(data, <span class="dt">ddvar =</span> <span class="st">"crest_dd"</span>, <span class="dt">ffvar =</span> <span class="st">"crest_ff"</span>,
         <span class="dt">windsector =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="st">"south wind"</span> =<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">90</span>, <span class="dv">270</span>)),
         <span class="dt">main =</span> <span class="st">"Windrose Sattelberg"</span>, <span class="dt">hue =</span> <span class="dv">270</span>,
         <span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, <span class="dv">35</span>, <span class="dt">by =</span> <span class="dv">5</span>))</code></pre></div>
<p><img src="ellboegen_files/figure-html/windsector_windrose-1.png" width="1152"></p>
</div>
<div id="estimate-classification-model" class="section level1">
<h1 class="hasAnchor">
<a href="#estimate-classification-model" class="anchor"></a>Estimate Classification Model</h1>
<p>The most important step is to estimate the <a href="references/foehnix.html"><code>foehnix</code></a> classification model. We use the following model assumptions:</p>
<ul>
<li>
<strong>Main variable</strong>: <code>diff_t</code> is used as the main covariate to separate ‘foehn’ from ‘no foehn’ events (potential temperature difference).</li>
<li>
<strong>Concomitant variable</strong>: <code>rh</code> and <code>ff</code> at valley site (relative humidity and wind speed).</li>
<li>
<strong>Wind filters</strong>: two filters are defined. <code>dd = c(43, 223)</code> for Ellbögen and <code>crest_dd = c(90, 270)</code> for Sattelberg (see above).</li>
<li>
<strong>Option switch:</strong> <code>switch = TRUE</code> as high <code>diff_temp</code> indicate stable stratification (no foehn).</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Estimate the foehnix classification model</span>
filter &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">dd =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">43</span>, <span class="dv">223</span>), <span class="dt">crest_dd =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">90</span>, <span class="dv">270</span>))
mod &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(diff_t <span class="op">~</span><span class="st"> </span>rh <span class="op">+</span><span class="st"> </span>ff,
               <span class="dt">data   =</span> data,
               <span class="dt">switch =</span> <span class="ot">TRUE</span>,
               <span class="dt">filter =</span> filter)</code></pre></div>
<div id="model-summary" class="section level3">
<h3 class="hasAnchor">
<a href="#model-summary" class="anchor"></a>Model Summary</h3>
<pre><code>## 
## Call: foehnix(formula = diff_t ~ rh + ff, data = data, switch = TRUE, 
##     filter = filter)
## 
## Number of observations (total)   113952 (5527 due to inflation)
## Removed due to missing values     38859 (34.1 percent)
## Outside defined wind sector       50665 (44.5 percent)
## Used for classification           24428 (21.4 percent)
## 
## Climatological foehn occurance 18.36 percent (on n = 75093)
## Mean foehn probability 18.06 percent (on n = 75093)
## 
## Log-likelihood: -55044.0, 7 effective degrees of freedom
## Corresponding AIC = 110101.9, BIC = 110158.6
## Time required for model estimation: 3.8 seconds
## 
## Cluster separation (ratios close to 1 indicate
## well separated clusters):
##                        prior  size post&gt;0 ratio
## Component 1 (foehn)     0.56 13785  19437  0.71
## Component 2 (no foehn)  0.44 10643  22764  0.47
## 
## ---------------------------------
## 
## Concomitant model: z test of coefficients
##                 Estimate Std. error   z value  Pr(&gt;|z|)    
## cc.(Intercept)  0.812721   0.105710    7.6882 1.492e-14 ***
## cc.rh          -1.029320   0.001446 -711.8479 &lt; 2.2e-16 ***
## cc.ff           3.305436   0.012134  272.4222 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## Number of IWLS iterations: 2 (algorithm converged)
## Dispersion parameter for binomial family taken to be 1.</code></pre>
<p>The data set contains <span class="math inline">\(N = 113952\)</span> observations, <span class="math inline">\(108425\)</span> from the data set itself (<code>data</code>) and <span class="math inline">\(5527\)</span> due to inflation used to make the time series object strictly regular.</p>
<p>Due to missing data <span class="math inline">\(38859\)</span> observations are not considered during model estimation (<code>dd</code>, <code>crest_dd</code>, <code>diff_t</code>, <code>rh</code>, or <code>ff</code> missing), <span class="math inline">\(50665\)</span> and are not included in model estimation as they do not lie within the defined wind sectors (<code>filter</code>). Thus, the <a href="references/foehnix.html"><code>foehnix</code></a> model is based on a total number of <span class="math inline">\(24428\)</span> observations (or rows).</p>
<p>Once we have estimated the model we can check whether or not the two clusters are well separated (foehn and no foehn). This can be done by checking the “<em>Cluster separation</em>” summary provided by <a href="references/summary.html"><code>summary</code></a> or checking the posterior probability plot:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Cluster separation (summary)</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(mod)<span class="op">$</span>separation</code></pre></div>
<pre><code>##                            prior  size post&gt;0     ratio
## Component 1 (foehn)    0.5596183 13785  19437 0.7092144
## Component 2 (no foehn) 0.4403817 10643  22764 0.4675365</code></pre>
<p>The <code>separation</code> matrix shows the prior probabilities, the size (number of observations assigned to each component; posterior probability), number of probabilities exceeding a threshold (default <code>eps = 1e-4</code>), and the ratio between the latter two. Ratios close to <span class="math inline">\(1.0\)</span> indicate that the two clusters are well separated (<span class="math inline">\(ratio &gt; 0.5\)</span> are already good for this application).</p>
<p>The “posterior probability histogram” (<code><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot(..., which = "posterior")</a></code>) shows the empirical histogram of estimated probabilities (for within-windsector observations). Point masses around <span class="math inline">\(0.0\)</span> and <span class="math inline">\(1.0\)</span> indicate that we have two well separated clusters (the probability to fall in one of the clusters is always close to either <span class="math inline">\(0\)</span> or <span class="math inline">\(1\)</span>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(mod, <span class="dt">which =</span> <span class="st">"posterior"</span>, <span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.05</span>)) </code></pre></div>
<p><img src="ellboegen_files/figure-html/unnamed-chunk-3-1.png" width="768"></p>
</div>
</div>
<div id="estimated-coefficients" class="section level1">
<h1 class="hasAnchor">
<a href="#estimated-coefficients" class="anchor"></a>Estimated Coefficients</h1>
<p>The following parameters are estimated for the two Gaussian clusters:</p>
<ul>
<li>No-foehn cluster: <span class="math inline">\(\mu_1 = 5.8\)</span>, <span class="math inline">\(\sigma_1 = 2.64\)</span> (parameter scale)</li>
<li>Foehn cluster: <span class="math inline">\(\mu_2 = 0.86\)</span>, <span class="math inline">\(\sigma_2 = 1.33\)</span> (parameter scale)</li>
<li>Concomitant model: positive <code>rh</code> effect of -5.3 percent per on relative humidity and a positive <code>ff</code> effect of +141.4 percent on wind speed</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/coef">coef</a></span>(mod)</code></pre></div>
<pre><code>## Coefficients of foehnix model
## Model formula:           diff_t ~ rh + ff
## foehnix family of class: Gaussian
## 
## Coefficients
##         mu1      sigma1         mu2      sigma2 (Intercept)          rh 
##  5.79908130  2.64068519  0.85860362  1.32845891 -1.19979850 -0.05476087 
##          ff 
##  0.88116142</code></pre>
<p>In other words: if the relative humidity increases the probability that we observed foehn decreases, while the probability increases with increasing wind speed.</p>
</div>
<div id="graphical-model-assessment" class="section level1">
<h1 class="hasAnchor">
<a href="#graphical-model-assessment" class="anchor"></a>Graphical Model Assessment</h1>
<p>A <a href="references/foehnix.html"><code>foehnix</code></a> object comes with generic plots for graphical model assessment.</p>
<p>The following figure shows the ‘log-likelihood contribution’ of</p>
<ul>
<li>the main <strong>component</strong> (left hand side of formula),</li>
<li>the <strong>concomitant</strong> model (right hand side of formula),</li>
<li>and the <strong>full</strong> log-likelihood sum which is maximised by the optimization algorithm.</li>
</ul>
<p>The abscissa shows (by default) the logarithm of the iterations during optimization.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Log-likelihood contribution</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(mod, <span class="dt">which =</span> <span class="st">"loglikcontribution"</span>)</code></pre></div>
<p><img src="ellboegen_files/figure-html/plot_loglikcontribution-1.png" width="1152"></p>
<p>In addition, the coefficient paths during optimization can be visualized:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Coefficient path</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(mod, <span class="dt">which =</span> 3L)</code></pre></div>
<p><img src="ellboegen_files/figure-html/plot_coefpath-1.png" width="1152"></p>
<p>The left plot shows the parameters of the two components (<span class="math inline">\(\mu_1\)</span>, <span class="math inline">\(\log(\sigma_1)\)</span>, <span class="math inline">\(\mu_2\)</span>, <span class="math inline">\(\log(\sigma_2)\)</span>), the right one the standardized coefficients of the concomitant model.</p>
<p>Last but not least a histogram with the two clusters is plotted. <code>which = "hist"</code>creates an empirical density histogram separating “no foehn” and “foehn” events adding the estimated distribution for these two clusters.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(mod, <span class="dt">which =</span> <span class="st">"hist"</span>)</code></pre></div>
<p><img src="ellboegen_files/figure-html/plot_histogram-1.png" width="768"></p>
</div>
<div id="time-series-plot" class="section level1">
<h1 class="hasAnchor">
<a href="#time-series-plot" class="anchor"></a>Time Series Plot</h1>
<p>The Californian demo data set has non-standard variable names (by purpose). Thus, when calling <code>tsplot</code> (time series plot) we do have to manually specify these names.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Some smaller quality issues in the data (should not be a big deal)</span>
start &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.POSIXlt">as.POSIXct</a></span>(<span class="st">"2017-02-01"</span>)
end   &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.POSIXlt">as.POSIXct</a></span>(<span class="st">"2017-02-12"</span>)

<span class="co"># As we dont have the standard names: re-specify variable names.</span>
<span class="co"># In addition, use 'style = "advanced"' to show more details.</span>
<span class="kw"><a href="../reference/tsplot.html">tsplot</a></span>(mod, <span class="dt">style =</span> <span class="st">"advanced"</span>, 
       <span class="dt">windsector =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">43</span>, <span class="dv">223</span>)),
       <span class="dt">start =</span> start, <span class="dt">end =</span> end)</code></pre></div>
<p><img src="ellboegen_files/figure-html/tsplot-1.png" width="1152"></p>
</div>
<div id="wind-rose-plot" class="section level1">
<h1 class="hasAnchor">
<a href="#wind-rose-plot" class="anchor"></a>Wind Rose Plot</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">devtools<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/devtools/topics/load_all">load_all</a></span>(<span class="st">".."</span>)</code></pre></div>
<pre><code>## Loading foehnix</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/windrose.html">windrose</a></span>(mod,
         <span class="dt">type =</span> <span class="st">"hist"</span>, <span class="dt">which =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"foehn"</span>, <span class="st">"nofoehn"</span>),
         <span class="dt">windsector =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">43</span>, <span class="dv">223</span>)),
         <span class="dt">breaks =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">0</span>, <span class="dv">22</span>, <span class="dt">by =</span> <span class="dv">2</span>))</code></pre></div>
<p><img src="ellboegen_files/figure-html/windrose-1.png" width="1152"></p>
</div>
<div id="hovmoler-diagram" class="section level1">
<h1 class="hasAnchor">
<a href="#hovmoler-diagram" class="anchor"></a>Hovmöler Diagram</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Default image plot</span>
<span class="kw"><a href="../reference/image.html">image</a></span>(mod)</code></pre></div>
<p><img src="ellboegen_files/figure-html/image1-1.png" width="1152"></p>
<p>Customized plot which shows the “foehn frequency” for the interesting time period from August to April with custom colors and additional contour lines and custom aggregation period (two-weeks, 3-hourly).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Customizing image plot</span>
devtools<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/devtools/topics/load_all">load_all</a></span>(<span class="st">".."</span>)</code></pre></div>
<pre><code>## Loading foehnix</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../reference/image.html">image</a></span>(mod, <span class="dt">deltad =</span> 10L, <span class="dt">deltat =</span> <span class="dv">2</span><span class="op">*</span><span class="dv">3600</span>, <span class="dt">contours =</span> <span class="ot">TRUE</span>,
      <span class="dt">contour.col =</span> <span class="st">"white"</span>, <span class="dt">lwd =</span> <span class="dv">2</span>, <span class="dt">labcex =</span> <span class="fl">1.5</span>,
      <span class="dt">col =</span> colorspace<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/colorspace/topics/hcl_palettes">sequential_hcl</a></span>(<span class="dv">51</span>, <span class="st">"Purple-Yellow"</span>, <span class="dt">rev =</span> <span class="ot">TRUE</span>),
      <span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">212</span>, <span class="dv">119</span>), <span class="dt">zlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">0</span>, <span class="fl">0.5</span>))</code></pre></div>
<p><img src="ellboegen_files/figure-html/image2-1.png" width="1152"></p>
</div>
<div id="compare-models-gaussian" class="section level1">
<h1 class="hasAnchor">
<a href="#compare-models-gaussian" class="anchor"></a>Compare Models (Gaussian)</h1>
<p>The model above (<code>diff_t ~ rh + ff</code>) fits this station well, however, we could of course change the model specifications. Let us specify a second model solely based on the target station (valley site). This can be important in practice if:</p>
<ul>
<li>A upstream crest station is not available.</li>
<li>The data availability for the crest station is limited due to outages, is no longer maintained, or has been installed much later than the valley station.</li>
</ul>
<p>Thus, we estimate a second model <code>mod_valley</code> using the following model specification:</p>
<ul>
<li>Data set: Ellbögen (<code>ell</code>; <code><a href="../reference/demodata.html">demodata("ellboegen")</a></code>)</li>
<li>Main variable: <code>ff</code> (wind speed)</li>
<li>Concomitants: <code>rf</code> (relative humidity)</li>
<li>Wind filter: <code>dd</code> <span class="math inline">\(\in [43, 223]\)</span> (as above)</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Load demo data set</span>
ell &lt;-<span class="st"> </span><span class="kw"><a href="../reference/demodata.html">demodata</a></span>(<span class="st">"ellboegen"</span>)
<span class="co"># Estimate alternative model</span>
mod_valley &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(ff <span class="op">~</span><span class="st"> </span>rh, <span class="dt">data =</span> ell,
                      <span class="dt">filter =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">dd =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">43</span>, <span class="dv">223</span>)))</code></pre></div>
<pre><code>## Calling foehnix.unreg.fit
## EM iteration 1/100, ll = -116585.87
 EM iteration 1/100, ll =  -22372.25
 EM iteration 1/100, ll = -138958.12
EM iteration 2/100, ll = -111699.60
 EM iteration 2/100, ll =  -22198.13
 EM iteration 2/100, ll = -133897.74
EM iteration 3/100, ll = -109626.44
 EM iteration 3/100, ll =  -22523.17
 EM iteration 3/100, ll = -132149.61
EM iteration 4/100, ll = -108899.30
 EM iteration 4/100, ll =  -22782.19
 EM iteration 4/100, ll = -131681.50
EM iteration 5/100, ll = -108736.65
 EM iteration 5/100, ll =  -22894.40
 EM iteration 5/100, ll = -131631.04
EM iteration 6/100, ll = -108804.98
 EM iteration 6/100, ll =  -22898.67
 EM iteration 6/100, ll = -131703.65
## Estimation finished, create final object</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(mod_valley, <span class="dt">which =</span> <span class="st">"hist"</span>)</code></pre></div>
<p><img src="ellboegen_files/figure-html/mod_valley-1.png" width="768"></p>
<p>To compare the performance of the two models we can calculate a set of information criterion. The following matrix shows the sample size (<code>N</code>), log-likelihood sum (<code>loglik</code>), Akaike information criterion (<code>AIC</code>), Bayesian information criterion (<code>BIC</code>), and ignorance (<code>IGN</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">get_IC &lt;-<span class="st"> </span><span class="cf">function</span>(x) <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dt">N =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(x<span class="op">$</span>filter_obj<span class="op">$</span>good), <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/logLik">logLik</a></span>(x), <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/AIC">AIC</a></span>(x), <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/AIC">BIC</a></span>(x), <span class="kw"><a href="../reference/IGN.html">IGN</a></span>(x))
IC &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">sapply</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">mod =</span> mod, <span class="dt">mod_valley =</span> mod_valley), get_IC)
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Round">round</a></span>(IC, <span class="dv">1</span>)</code></pre></div>
<pre><code>##             mod mod_valley
## N       24428.0    52390.0
## loglik -55044.0  -131631.0
## AIC    110101.9   263274.1
## BIC    110158.6   263327.3
## IGN         2.3        2.5</code></pre>
<p><strong>Warning:</strong> due to the model specification the two models are based on different data sets (sample size strongly differs). Thus, we <em>cannot directly compare the models</em> using <code>loglik</code>, <code>AIC</code>, or <code>BIC</code>. <code>IGN</code> accounts for the sample size (mean negative log-likelihood), however, as the two models include different training data sets this is inconclusive.</p>
<p>For a fair and reliable comparison one should estimate both models on the very same data set, e.g., as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Load the demo data set once more</span>
data_for_comparison &lt;-<span class="st"> </span><span class="kw"><a href="../reference/demodata.html">demodata</a></span>(<span class="st">"tyrol"</span>)
<span class="co"># Extract the required variables</span>
data_for_comparison &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/subset">subset</a></span>(data_for_comparison, <span class="dt">select =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(dd, ff, rh, diff_t, crest_dd))
<span class="co"># Remove all observations (rows) with missing values</span>
data_for_comparison &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/na.fail">na.omit</a></span>(data_for_comparison)

<span class="co"># Estimate alternative model "mod_comparison"</span>
<span class="co"># Note: using dd/crest_dd filter for both models (required to</span>
<span class="co"># end up with the same sample size)</span>
filter &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">dd =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">43</span>, <span class="dv">223</span>), <span class="dt">crest_dd =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">90</span>, <span class="dv">270</span>))
mod_comparison        &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/formula">formula</a></span>(mod),
                                 <span class="dt">data =</span> data_for_comparison,
                                 <span class="dt">filter =</span> filter)</code></pre></div>
<pre><code>## Calling foehnix.unreg.fit
## EM iteration 1/100, ll =  -50413.45
 EM iteration 1/100, ll =   -6417.57
 EM iteration 1/100, ll =  -56831.02
EM iteration 2/100, ll =  -49253.02
 EM iteration 2/100, ll =   -6049.06
 EM iteration 2/100, ll =  -55302.09
EM iteration 3/100, ll =  -49045.42
 EM iteration 3/100, ll =   -6022.55
 EM iteration 3/100, ll =  -55067.97
EM iteration 4/100, ll =  -48995.41
 EM iteration 4/100, ll =   -6048.54
 EM iteration 4/100, ll =  -55043.95
EM iteration 5/100, ll =  -48975.44
 EM iteration 5/100, ll =   -6080.42
 EM iteration 5/100, ll =  -55055.86
## Estimation finished, create final object</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod_valley_comparison &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/formula">formula</a></span>(mod_valley),
                                 <span class="dt">data =</span> data_for_comparison,
                                 <span class="dt">filter =</span> filter)</code></pre></div>
<pre><code>## Calling foehnix.unreg.fit
## EM iteration 1/100, ll =  -58847.82
 EM iteration 1/100, ll =  -12700.17
 EM iteration 1/100, ll =  -71547.98
EM iteration 2/100, ll =  -57448.95
 EM iteration 2/100, ll =  -12209.81
 EM iteration 2/100, ll =  -69658.76
EM iteration 3/100, ll =  -56440.92
 EM iteration 3/100, ll =  -11986.48
 EM iteration 3/100, ll =  -68427.40
EM iteration 4/100, ll =  -55737.86
 EM iteration 4/100, ll =  -11858.49
 EM iteration 4/100, ll =  -67596.35
EM iteration 5/100, ll =  -55275.52
 EM iteration 5/100, ll =  -11740.68
 EM iteration 5/100, ll =  -67016.20
EM iteration 6/100, ll =  -55007.66
 EM iteration 6/100, ll =  -11605.70
 EM iteration 6/100, ll =  -66613.36
EM iteration 7/100, ll =  -54890.22
 EM iteration 7/100, ll =  -11451.18
 EM iteration 7/100, ll =  -66341.40
EM iteration 8/100, ll =  -54879.55
 EM iteration 8/100, ll =  -11283.43
 EM iteration 8/100, ll =  -66162.98
EM iteration 9/100, ll =  -54937.29
 EM iteration 9/100, ll =  -11110.68
 EM iteration 9/100, ll =  -66047.97
EM iteration 10/100, ll =  -55033.61
 EM iteration 10/100, ll =  -10940.41
 EM iteration 10/100, ll =  -65974.03
EM iteration 11/100, ll =  -55147.60
 EM iteration 11/100, ll =  -10778.30
 EM iteration 11/100, ll =  -65925.90
EM iteration 12/100, ll =  -55265.72
 EM iteration 12/100, ll =  -10628.05
 EM iteration 12/100, ll =  -65893.77
EM iteration 13/100, ll =  -55379.91
 EM iteration 13/100, ll =  -10491.69
 EM iteration 13/100, ll =  -65871.60
EM iteration 14/100, ll =  -55485.74
 EM iteration 14/100, ll =  -10369.96
 EM iteration 14/100, ll =  -65855.70
EM iteration 15/100, ll =  -55581.22
 EM iteration 15/100, ll =  -10262.67
 EM iteration 15/100, ll =  -65843.88
EM iteration 16/100, ll =  -55665.75
 EM iteration 16/100, ll =  -10169.06
 EM iteration 16/100, ll =  -65834.81
EM iteration 17/100, ll =  -55739.62
 EM iteration 17/100, ll =  -10088.03
 EM iteration 17/100, ll =  -65827.65
EM iteration 18/100, ll =  -55803.55
 EM iteration 18/100, ll =  -10018.33
 EM iteration 18/100, ll =  -65821.89
EM iteration 19/100, ll =  -55858.49
 EM iteration 19/100, ll =   -9958.70
 EM iteration 19/100, ll =  -65817.18
EM iteration 20/100, ll =  -55905.44
 EM iteration 20/100, ll =   -9907.87
 EM iteration 20/100, ll =  -65813.31
EM iteration 21/100, ll =  -55945.40
 EM iteration 21/100, ll =   -9864.70
 EM iteration 21/100, ll =  -65810.10
EM iteration 22/100, ll =  -55979.29
 EM iteration 22/100, ll =   -9828.12
 EM iteration 22/100, ll =  -65807.42
EM iteration 23/100, ll =  -56007.97
 EM iteration 23/100, ll =   -9797.21
 EM iteration 23/100, ll =  -65805.18
EM iteration 24/100, ll =  -56032.19
 EM iteration 24/100, ll =   -9771.12
 EM iteration 24/100, ll =  -65803.30
EM iteration 25/100, ll =  -56052.60
 EM iteration 25/100, ll =   -9749.14
 EM iteration 25/100, ll =  -65801.73
EM iteration 26/100, ll =  -56069.78
 EM iteration 26/100, ll =   -9730.64
 EM iteration 26/100, ll =  -65800.42
EM iteration 27/100, ll =  -56084.23
 EM iteration 27/100, ll =   -9715.09
 EM iteration 27/100, ll =  -65799.32
EM iteration 28/100, ll =  -56096.37
 EM iteration 28/100, ll =   -9702.03
 EM iteration 28/100, ll =  -65798.39
EM iteration 29/100, ll =  -56106.56
 EM iteration 29/100, ll =   -9691.06
 EM iteration 29/100, ll =  -65797.62
EM iteration 30/100, ll =  -56115.11
 EM iteration 30/100, ll =   -9681.86
 EM iteration 30/100, ll =  -65796.97
EM iteration 31/100, ll =  -56122.28
 EM iteration 31/100, ll =   -9674.15
 EM iteration 31/100, ll =  -65796.43
EM iteration 32/100, ll =  -56128.28
 EM iteration 32/100, ll =   -9667.69
 EM iteration 32/100, ll =  -65795.97
EM iteration 33/100, ll =  -56133.32
 EM iteration 33/100, ll =   -9662.28
 EM iteration 33/100, ll =  -65795.59
EM iteration 34/100, ll =  -56137.53
 EM iteration 34/100, ll =   -9657.74
 EM iteration 34/100, ll =  -65795.27
EM iteration 35/100, ll =  -56141.07
 EM iteration 35/100, ll =   -9653.94
 EM iteration 35/100, ll =  -65795.00
EM iteration 36/100, ll =  -56144.02
 EM iteration 36/100, ll =   -9650.76
 EM iteration 36/100, ll =  -65794.78
EM iteration 37/100, ll =  -56146.50
 EM iteration 37/100, ll =   -9648.09
 EM iteration 37/100, ll =  -65794.59
EM iteration 38/100, ll =  -56148.58
 EM iteration 38/100, ll =   -9645.86
 EM iteration 38/100, ll =  -65794.44
EM iteration 39/100, ll =  -56150.31
 EM iteration 39/100, ll =   -9643.99
 EM iteration 39/100, ll =  -65794.31
EM iteration 40/100, ll =  -56151.76
 EM iteration 40/100, ll =   -9642.43
 EM iteration 40/100, ll =  -65794.20
EM iteration 41/100, ll =  -56152.98
 EM iteration 41/100, ll =   -9641.12
 EM iteration 41/100, ll =  -65794.10
EM iteration 42/100, ll =  -56154.00
 EM iteration 42/100, ll =   -9640.03
 EM iteration 42/100, ll =  -65794.03
EM iteration 43/100, ll =  -56154.85
 EM iteration 43/100, ll =   -9639.11
 EM iteration 43/100, ll =  -65793.96
EM iteration 44/100, ll =  -56155.56
 EM iteration 44/100, ll =   -9638.35
 EM iteration 44/100, ll =  -65793.91
EM iteration 45/100, ll =  -56156.16
 EM iteration 45/100, ll =   -9637.71
 EM iteration 45/100, ll =  -65793.86
EM iteration 46/100, ll =  -56156.65
 EM iteration 46/100, ll =   -9637.17
 EM iteration 46/100, ll =  -65793.83
EM iteration 47/100, ll =  -56157.07
 EM iteration 47/100, ll =   -9636.72
 EM iteration 47/100, ll =  -65793.79
EM iteration 48/100, ll =  -56157.42
 EM iteration 48/100, ll =   -9636.35
 EM iteration 48/100, ll =  -65793.77
EM iteration 49/100, ll =  -56157.71
 EM iteration 49/100, ll =   -9636.03
 EM iteration 49/100, ll =  -65793.75
EM iteration 50/100, ll =  -56157.96
 EM iteration 50/100, ll =   -9635.77
 EM iteration 50/100, ll =  -65793.73
EM iteration 51/100, ll =  -56158.16
 EM iteration 51/100, ll =   -9635.55
 EM iteration 51/100, ll =  -65793.71
EM iteration 52/100, ll =  -56158.33
 EM iteration 52/100, ll =   -9635.37
 EM iteration 52/100, ll =  -65793.70
EM iteration 53/100, ll =  -56158.47
 EM iteration 53/100, ll =   -9635.21
 EM iteration 53/100, ll =  -65793.69
EM iteration 54/100, ll =  -56158.59
 EM iteration 54/100, ll =   -9635.09
 EM iteration 54/100, ll =  -65793.68
EM iteration 55/100, ll =  -56158.69
 EM iteration 55/100, ll =   -9634.98
 EM iteration 55/100, ll =  -65793.67
EM iteration 56/100, ll =  -56158.78
 EM iteration 56/100, ll =   -9634.89
 EM iteration 56/100, ll =  -65793.67
EM iteration 57/100, ll =  -56158.85
 EM iteration 57/100, ll =   -9634.81
 EM iteration 57/100, ll =  -65793.66
EM iteration 58/100, ll =  -56158.91
 EM iteration 58/100, ll =   -9634.75
 EM iteration 58/100, ll =  -65793.66
EM iteration 59/100, ll =  -56158.95
 EM iteration 59/100, ll =   -9634.70
 EM iteration 59/100, ll =  -65793.65
EM iteration 60/100, ll =  -56159.00
 EM iteration 60/100, ll =   -9634.65
 EM iteration 60/100, ll =  -65793.65
EM iteration 61/100, ll =  -56159.03
 EM iteration 61/100, ll =   -9634.62
 EM iteration 61/100, ll =  -65793.65
EM iteration 62/100, ll =  -56159.06
 EM iteration 62/100, ll =   -9634.59
 EM iteration 62/100, ll =  -65793.64
EM iteration 63/100, ll =  -56159.08
 EM iteration 63/100, ll =   -9634.56
 EM iteration 63/100, ll =  -65793.64
EM iteration 64/100, ll =  -56159.10
 EM iteration 64/100, ll =   -9634.54
 EM iteration 64/100, ll =  -65793.64
EM iteration 65/100, ll =  -56159.12
 EM iteration 65/100, ll =   -9634.52
 EM iteration 65/100, ll =  -65793.64
EM iteration 66/100, ll =  -56159.13
 EM iteration 66/100, ll =   -9634.51
 EM iteration 66/100, ll =  -65793.64
EM iteration 67/100, ll =  -56159.14
 EM iteration 67/100, ll =   -9634.49
 EM iteration 67/100, ll =  -65793.64
EM iteration 68/100, ll =  -56159.15
 EM iteration 68/100, ll =   -9634.48
 EM iteration 68/100, ll =  -65793.64
EM iteration 69/100, ll =  -56159.16
 EM iteration 69/100, ll =   -9634.47
 EM iteration 69/100, ll =  -65793.64
EM iteration 70/100, ll =  -56159.17
 EM iteration 70/100, ll =   -9634.47
 EM iteration 70/100, ll =  -65793.64
EM iteration 71/100, ll =  -56159.18
 EM iteration 71/100, ll =   -9634.46
 EM iteration 71/100, ll =  -65793.64
EM iteration 72/100, ll =  -56159.18
 EM iteration 72/100, ll =   -9634.46
 EM iteration 72/100, ll =  -65793.64
EM iteration 73/100, ll =  -56159.18
 EM iteration 73/100, ll =   -9634.45
 EM iteration 73/100, ll =  -65793.64
EM iteration 74/100, ll =  -56159.19
 EM iteration 74/100, ll =   -9634.45
 EM iteration 74/100, ll =  -65793.63
EM iteration 75/100, ll =  -56159.19
 EM iteration 75/100, ll =   -9634.44
 EM iteration 75/100, ll =  -65793.63
EM iteration 76/100, ll =  -56159.19
 EM iteration 76/100, ll =   -9634.44
 EM iteration 76/100, ll =  -65793.63
EM iteration 77/100, ll =  -56159.19
 EM iteration 77/100, ll =   -9634.44
 EM iteration 77/100, ll =  -65793.63
EM iteration 78/100, ll =  -56159.20
 EM iteration 78/100, ll =   -9634.44
 EM iteration 78/100, ll =  -65793.63
EM iteration 79/100, ll =  -56159.20
 EM iteration 79/100, ll =   -9634.44
 EM iteration 79/100, ll =  -65793.63
EM iteration 80/100, ll =  -56159.20
 EM iteration 80/100, ll =   -9634.44
 EM iteration 80/100, ll =  -65793.63
EM iteration 81/100, ll =  -56159.20
 EM iteration 81/100, ll =   -9634.43
 EM iteration 81/100, ll =  -65793.63
EM iteration 82/100, ll =  -56159.20
 EM iteration 82/100, ll =   -9634.43
 EM iteration 82/100, ll =  -65793.63
EM iteration 83/100, ll =  -56159.20
 EM iteration 83/100, ll =   -9634.43
 EM iteration 83/100, ll =  -65793.63
EM iteration 84/100, ll =  -56159.20
 EM iteration 84/100, ll =   -9634.43
 EM iteration 84/100, ll =  -65793.63
EM iteration 85/100, ll =  -56159.20
 EM iteration 85/100, ll =   -9634.43
 EM iteration 85/100, ll =  -65793.63
EM iteration 86/100, ll =  -56159.20
 EM iteration 86/100, ll =   -9634.43
 EM iteration 86/100, ll =  -65793.63
EM iteration 87/100, ll =  -56159.20
 EM iteration 87/100, ll =   -9634.43
 EM iteration 87/100, ll =  -65793.63
EM iteration 88/100, ll =  -56159.20
 EM iteration 88/100, ll =   -9634.43
 EM iteration 88/100, ll =  -65793.63
EM iteration 89/100, ll =  -56159.20
 EM iteration 89/100, ll =   -9634.43
 EM iteration 89/100, ll =  -65793.63
EM iteration 90/100, ll =  -56159.20
 EM iteration 90/100, ll =   -9634.43
 EM iteration 90/100, ll =  -65793.63
EM iteration 91/100, ll =  -56159.20
 EM iteration 91/100, ll =   -9634.43
 EM iteration 91/100, ll =  -65793.63
EM iteration 92/100, ll =  -56159.20
 EM iteration 92/100, ll =   -9634.43
 EM iteration 92/100, ll =  -65793.63
EM iteration 93/100, ll =  -56159.20
 EM iteration 93/100, ll =   -9634.43
 EM iteration 93/100, ll =  -65793.63
EM iteration 94/100, ll =  -56159.20
 EM iteration 94/100, ll =   -9634.43
 EM iteration 94/100, ll =  -65793.63
EM iteration 95/100, ll =  -56159.20
 EM iteration 95/100, ll =   -9634.43
 EM iteration 95/100, ll =  -65793.63
EM iteration 96/100, ll =  -56159.20
 EM iteration 96/100, ll =   -9634.43
 EM iteration 96/100, ll =  -65793.63
EM iteration 97/100, ll =  -56159.20
 EM iteration 97/100, ll =   -9634.43
 EM iteration 97/100, ll =  -65793.63
EM iteration 98/100, ll =  -56159.20
 EM iteration 98/100, ll =   -9634.43
 EM iteration 98/100, ll =  -65793.63
EM iteration 99/100, ll =  -56159.20
 EM iteration 99/100, ll =   -9634.43
 EM iteration 99/100, ll =  -65793.63
EM iteration 100/100, ll =  -56159.20
 EM iteration 100/100, ll =   -9634.43
 EM iteration 100/100, ll =  -65793.63
## Estimation finished, create final object</code></pre>
<p>Again, calculate the information criteria:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Information criteria</span>
IC &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">sapply</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">mod_comparison =</span> mod_comparison,
                  <span class="dt">mod_valley_comparison =</span> mod_valley_comparison), get_IC)
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Round">round</a></span>(IC, <span class="dv">1</span>)</code></pre></div>
<pre><code>##        mod_comparison mod_valley_comparison
## N             24428.0               24428.0
## loglik       -55044.0              -65793.6
## AIC          110101.9              131599.3
## BIC          110158.6              131647.9
## IGN               2.3                   2.7</code></pre>
<p>Both models are now based on the same sample (<span class="math inline">\(N = 2.4428\times 10^{4}\)</span>). Thus, we can compare the different scores. The more complex model (<code>mod_comparison</code>) outperforms the one solely based on observations from the valley site. Thus, the model <code>mod</code> should be preferred over the simpler one. However, in practice it is often useful to have both (more than one) model to fill in periods where e.g., the crest station does not provide data.</p>
<p>To fill gaps (missing values in the classification of model <code>mod</code>) we could combine the estimates of both models:</p>
<ul>
<li>First, take probabilities from model <code>mod</code>. If not available,</li>
<li>take estimates from model <code>mod_valley</code>.</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Combine results of both models:</span>
prob &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/merge">merge</a></span>(<span class="dt">mod =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/fitted.values">fitted</a></span>(mod), <span class="dt">mod_valley =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/fitted.values">fitted</a></span>(mod_valley))

<span class="co"># Number of missing entries</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/apply">apply</a></span>(prob, <span class="dv">2</span>, <span class="cf">function</span>(x) <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(x)))</code></pre></div>
<pre><code>##        mod mod_valley 
##      38859      11162</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># For demonstration purposes: find rows where mod is missing</span>
<span class="co"># while mod_valley returns a probability:</span>
idx &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which">which</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(prob<span class="op">$</span>mod) <span class="op">&amp;</span><span class="st"> </span><span class="op">!</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(prob<span class="op">$</span>mod_valley))[1L] <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>)
<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(prob[idx, ])</code></pre></div>
<pre><code>##                     mod  mod_valley
## 2006-01-01 07:00:00   0 0.000000000
## 2006-01-01 08:00:00   0 0.000000000
## 2006-01-01 09:00:00   0 0.000000000
## 2006-01-01 10:00:00  NA 0.001756782
## 2006-01-01 11:00:00   0 0.001629606
## 2006-01-01 12:00:00   0 0.000000000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Combine the two (take probability from mod if available,</span>
<span class="co"># else from mod_valley; both missing: NA).</span>
combine_prob &lt;-<span class="st"> </span><span class="cf">function</span>(x) {
    <span class="cf">if</span> (<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/all">all</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(x))) <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/function">return</a></span>(<span class="ot">NA</span>)
    <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/function">return</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/na.fail">na.omit</a></span>(x), <span class="dt">n =</span> <span class="dv">1</span>))
}
prob &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/apply">apply</a></span>(prob, <span class="dv">1</span>, combine_prob)
<span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/head">head</a></span>(prob[idx])</code></pre></div>
<pre><code>## 2006-01-01 07:00:00 2006-01-01 08:00:00 2006-01-01 09:00:00 
##         0.000000000         0.000000000         0.000000000 
## 2006-01-01 10:00:00 2006-01-01 11:00:00 2006-01-01 12:00:00 
##         0.001756782         0.000000000         0.000000000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Check missing values</span>
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/sum">sum</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(prob))</code></pre></div>
<pre><code>## [1] 11162</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">start &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.POSIXlt">as.POSIXct</a></span>(<span class="st">"2010-02-01"</span>)
end   &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.POSIXlt">as.POSIXct</a></span>(<span class="st">"2010-02-15"</span>)

<span class="co"># Time series plot to compare "mod" (the most complex model)</span>
<span class="co"># and the four alternatives.</span>
<span class="kw"><a href="../reference/tsplot.html">tsplot</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">mod =</span> mod, <span class="dt">mod_valley =</span> mod_valley),
       <span class="dt">style =</span> <span class="st">"advanced"</span>,
       <span class="dt">windsector =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">dd =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">43</span>, <span class="dv">223</span>)),
       <span class="dt">start =</span> start, <span class="dt">end =</span> end)</code></pre></div>
<p><img src="ellboegen_files/figure-html/alt_tsplot-1.png" width="1152"></p>
</div>
<div id="compare-models-distributions" class="section level1">
<h1 class="hasAnchor">
<a href="#compare-models-distributions" class="anchor"></a>Compare Models (Distributions)</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Formula and wind direction filter specification</span>
filter  &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">dd =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">43</span>, <span class="dv">223</span>), <span class="dt">crest_dd =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">90</span>, <span class="dv">270</span>))
formula &lt;-<span class="st"> "ff ~ rh"</span>

<span class="co"># Gaussian models: Gaussian, left-censored Gaussian (at 0),</span>
<span class="co"># and left-truncated Gaussian (at 0). Note that, for demonstration</span>
<span class="co"># purposes, the censored/truncated models do 20 iterations.</span>
mod_gauss  &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(formula, <span class="dt">data =</span> data, <span class="dt">family =</span> <span class="st">"gaussian"</span>)</code></pre></div>
<pre><code>## Calling foehnix.unreg.fit
## EM iteration 1/100, ll = -209921.43
 EM iteration 1/100, ll =  -46974.77
 EM iteration 1/100, ll = -256896.20
EM iteration 2/100, ll = -202451.79
 EM iteration 2/100, ll =  -46329.96
 EM iteration 2/100, ll = -248781.75
EM iteration 3/100, ll = -199912.54
 EM iteration 3/100, ll =  -46846.60
 EM iteration 3/100, ll = -246759.14
EM iteration 4/100, ll = -198881.85
 EM iteration 4/100, ll =  -47419.53
 EM iteration 4/100, ll = -246301.37
EM iteration 5/100, ll = -198423.57
 EM iteration 5/100, ll =  -47850.85
 EM iteration 5/100, ll = -246274.42
EM iteration 6/100, ll = -198220.99
 EM iteration 6/100, ll =  -48147.21
 EM iteration 6/100, ll = -246368.20
## Estimation finished, create final object</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod_cgauss &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(formula, <span class="dt">data =</span> data, <span class="dt">family =</span> <span class="st">"gaussian"</span>,
                      <span class="dt">left =</span> <span class="dv">0</span>, <span class="dt">tol =</span> <span class="op">-</span><span class="ot">Inf</span>, <span class="dt">maxit =</span> <span class="dv">20</span>)</code></pre></div>
<pre><code>## Calling foehnix.unreg.fit</code></pre>
<pre><code>## Warning in iwls_logit(logitX, z, standardize = FALSE, maxit = tail(maxit, :
## IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 1/20, ll = -196388.00
 EM iteration 1/20, ll =  -53329.73
 EM iteration 1/20, ll = -249717.74</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 2/20, ll = -197875.58
 EM iteration 2/20, ll =  -51786.91
 EM iteration 2/20, ll = -249662.49</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 3/20, ll = -198652.34
 EM iteration 3/20, ll =  -50796.02
 EM iteration 3/20, ll = -249448.36</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 4/20, ll = -199050.46
 EM iteration 4/20, ll =  -50156.52
 EM iteration 4/20, ll = -249206.99</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 5/20, ll = -199243.84
 EM iteration 5/20, ll =  -49741.58
 EM iteration 5/20, ll = -248985.42</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 6/20, ll = -199331.69
 EM iteration 6/20, ll =  -49465.61
 EM iteration 6/20, ll = -248797.30</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 7/20, ll = -199353.19
 EM iteration 7/20, ll =  -49281.05
 EM iteration 7/20, ll = -248634.24</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 8/20, ll = -199339.71
 EM iteration 8/20, ll =  -49155.66
 EM iteration 8/20, ll = -248495.38</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 9/20, ll = -199308.82
 EM iteration 9/20, ll =  -49068.64
 EM iteration 9/20, ll = -248377.46</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 10/20, ll = -199270.58
 EM iteration 10/20, ll =  -49006.75
 EM iteration 10/20, ll = -248277.33</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 11/20, ll = -199222.54
 EM iteration 11/20, ll =  -48966.08
 EM iteration 11/20, ll = -248188.62</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 12/20, ll = -199180.81
 EM iteration 12/20, ll =  -48936.25
 EM iteration 12/20, ll = -248117.06</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 13/20, ll = -199143.91
 EM iteration 13/20, ll =  -48913.32
 EM iteration 13/20, ll = -248057.23</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 14/20, ll = -199111.55
 EM iteration 14/20, ll =  -48895.19
 EM iteration 14/20, ll = -248006.74</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 15/20, ll = -199083.41
 EM iteration 15/20, ll =  -48880.60
 EM iteration 15/20, ll = -247964.01</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 16/20, ll = -199059.12
 EM iteration 16/20, ll =  -48868.69
 EM iteration 16/20, ll = -247927.81</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 17/20, ll = -199038.27
 EM iteration 17/20, ll =  -48858.86
 EM iteration 17/20, ll = -247897.13</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 18/20, ll = -199020.45
 EM iteration 18/20, ll =  -48850.69
 EM iteration 18/20, ll = -247871.14</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 19/20, ll = -199005.26
 EM iteration 19/20, ll =  -48843.86
 EM iteration 19/20, ll = -247849.12</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 20/20, ll = -198992.34
 EM iteration 20/20, ll =  -48838.13
 EM iteration 20/20, ll = -247830.47
## Estimation finished, create final object</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod_tgauss &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(formula, <span class="dt">data =</span> data, <span class="dt">family =</span> <span class="st">"gaussian"</span>,
                      <span class="dt">left =</span> <span class="dv">0</span>, <span class="dt">tol =</span> <span class="op">-</span><span class="ot">Inf</span>, <span class="dt">maxit =</span> <span class="dv">20</span>, <span class="dt">truncated =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## Calling foehnix.unreg.fit</code></pre>
<pre><code>## Warning in iwls_logit(logitX, z, standardize = FALSE, maxit = tail(maxit, :
## IWLS solver for logistic model did not converge.

## Warning in iwls_logit(logitX, z, standardize = FALSE, maxit = tail(maxit, :
## IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 1/20, ll = -193772.74
 EM iteration 1/20, ll =  -52471.14
 EM iteration 1/20, ll = -246243.89</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 2/20, ll = -196008.19
 EM iteration 2/20, ll =  -50373.67
 EM iteration 2/20, ll = -246381.85</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 3/20, ll = -197524.79
 EM iteration 3/20, ll =  -48832.44
 EM iteration 3/20, ll = -246357.23</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 4/20, ll = -198601.48
 EM iteration 4/20, ll =  -47678.20
 EM iteration 4/20, ll = -246279.68</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 5/20, ll = -199405.35
 EM iteration 5/20, ll =  -46800.52
 EM iteration 5/20, ll = -246205.87</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 6/20, ll = -200030.71
 EM iteration 6/20, ll =  -46122.78
 EM iteration 6/20, ll = -246153.49</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 7/20, ll = -200533.14
 EM iteration 7/20, ll =  -45591.40
 EM iteration 7/20, ll = -246124.54</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 8/20, ll = -200948.50
 EM iteration 8/20, ll =  -45167.49
 EM iteration 8/20, ll = -246115.99</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 9/20, ll = -201298.73
 EM iteration 9/20, ll =  -44824.11
 EM iteration 9/20, ll = -246122.84</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 10/20, ll = -201599.32
 EM iteration 10/20, ll =  -44541.65
 EM iteration 10/20, ll = -246140.97</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 11/20, ll = -201861.17
 EM iteration 11/20, ll =  -44305.81
 EM iteration 11/20, ll = -246166.98</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 12/20, ll = -202092.12
 EM iteration 12/20, ll =  -44106.07
 EM iteration 12/20, ll = -246198.19</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 13/20, ll = -202297.92
 EM iteration 13/20, ll =  -43934.63
 EM iteration 13/20, ll = -246232.56</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 14/20, ll = -202480.61
 EM iteration 14/20, ll =  -43786.74
 EM iteration 14/20, ll = -246267.35</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 15/20, ll = -202646.49
 EM iteration 15/20, ll =  -43657.13
 EM iteration 15/20, ll = -246303.62</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 16/20, ll = -202797.77
 EM iteration 16/20, ll =  -43542.21
 EM iteration 16/20, ll = -246339.98</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 17/20, ll = -202936.31
 EM iteration 17/20, ll =  -43439.30
 EM iteration 17/20, ll = -246375.61</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 18/20, ll = -203063.67
 EM iteration 18/20, ll =  -43346.37
 EM iteration 18/20, ll = -246410.04</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 19/20, ll = -203181.14
 EM iteration 19/20, ll =  -43261.86
 EM iteration 19/20, ll = -246443.00</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 20/20, ll = -203289.76
 EM iteration 20/20, ll =  -43184.54
 EM iteration 20/20, ll = -246474.30
## Estimation finished, create final object</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Logistic models: logistic, left-censored logistic (at 0),</span>
<span class="co"># and left-truncated logistic (at 0). Again, fixed number of</span>
<span class="co"># iterations for the censored and truncated models.</span>
mod_logis  &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(formula, <span class="dt">data =</span> data, <span class="dt">family =</span> <span class="st">"logistic"</span>)</code></pre></div>
<pre><code>## Calling foehnix.unreg.fit
## EM iteration 1/100, ll = -208705.02
 EM iteration 1/100, ll =  -46194.27
 EM iteration 1/100, ll = -254899.30
EM iteration 2/100, ll = -202624.20
 EM iteration 2/100, ll =  -45533.52
 EM iteration 2/100, ll = -248157.73
EM iteration 3/100, ll = -200831.49
 EM iteration 3/100, ll =  -45816.36
 EM iteration 3/100, ll = -246647.85
EM iteration 4/100, ll = -200130.72
 EM iteration 4/100, ll =  -46113.01
 EM iteration 4/100, ll = -246243.74
EM iteration 5/100, ll = -199803.99
 EM iteration 5/100, ll =  -46307.36
 EM iteration 5/100, ll = -246111.34
EM iteration 6/100, ll = -199637.27
 EM iteration 6/100, ll =  -46419.74
 EM iteration 6/100, ll = -246057.01
EM iteration 7/100, ll = -199548.28
 EM iteration 7/100, ll =  -46480.88
 EM iteration 7/100, ll = -246029.16
EM iteration 8/100, ll = -199499.53
 EM iteration 8/100, ll =  -46512.65
 EM iteration 8/100, ll = -246012.18
EM iteration 9/100, ll = -199472.28
 EM iteration 9/100, ll =  -46528.26
 EM iteration 9/100, ll = -246000.54
EM iteration 10/100, ll = -199456.71
 EM iteration 10/100, ll =  -46535.25
 EM iteration 10/100, ll = -245991.95
EM iteration 11/100, ll = -199447.56
 EM iteration 11/100, ll =  -46537.72
 EM iteration 11/100, ll = -245985.29
EM iteration 12/100, ll = -199441.99
 EM iteration 12/100, ll =  -46537.94
 EM iteration 12/100, ll = -245979.93
EM iteration 13/100, ll = -199438.45
 EM iteration 13/100, ll =  -46537.09
 EM iteration 13/100, ll = -245975.53
EM iteration 14/100, ll = -199436.07
 EM iteration 14/100, ll =  -46535.79
 EM iteration 14/100, ll = -245971.86
EM iteration 15/100, ll = -199434.39
 EM iteration 15/100, ll =  -46534.38
 EM iteration 15/100, ll = -245968.77
EM iteration 16/100, ll = -199433.15
 EM iteration 16/100, ll =  -46533.00
 EM iteration 16/100, ll = -245966.14
EM iteration 17/100, ll = -199432.19
 EM iteration 17/100, ll =  -46531.72
 EM iteration 17/100, ll = -245963.91
EM iteration 18/100, ll = -199431.42
 EM iteration 18/100, ll =  -46530.58
 EM iteration 18/100, ll = -245962.00
EM iteration 19/100, ll = -199430.79
 EM iteration 19/100, ll =  -46529.57
 EM iteration 19/100, ll = -245960.36
EM iteration 20/100, ll = -199430.27
 EM iteration 20/100, ll =  -46528.69
 EM iteration 20/100, ll = -245958.96
EM iteration 21/100, ll = -199429.83
 EM iteration 21/100, ll =  -46527.93
 EM iteration 21/100, ll = -245957.75
EM iteration 22/100, ll = -199429.45
 EM iteration 22/100, ll =  -46527.27
 EM iteration 22/100, ll = -245956.72
EM iteration 23/100, ll = -199429.14
 EM iteration 23/100, ll =  -46526.70
 EM iteration 23/100, ll = -245955.83
EM iteration 24/100, ll = -199428.86
 EM iteration 24/100, ll =  -46526.21
 EM iteration 24/100, ll = -245955.07
EM iteration 25/100, ll = -199428.63
 EM iteration 25/100, ll =  -46525.79
 EM iteration 25/100, ll = -245954.42
EM iteration 26/100, ll = -199428.43
 EM iteration 26/100, ll =  -46525.43
 EM iteration 26/100, ll = -245953.86
EM iteration 27/100, ll = -199428.26
 EM iteration 27/100, ll =  -46525.11
 EM iteration 27/100, ll = -245953.38
EM iteration 28/100, ll = -199428.12
 EM iteration 28/100, ll =  -46524.85
 EM iteration 28/100, ll = -245952.96
EM iteration 29/100, ll = -199427.99
 EM iteration 29/100, ll =  -46524.62
 EM iteration 29/100, ll = -245952.61
EM iteration 30/100, ll = -199427.88
 EM iteration 30/100, ll =  -46524.42
 EM iteration 30/100, ll = -245952.30
EM iteration 31/100, ll = -199427.79
 EM iteration 31/100, ll =  -46524.25
 EM iteration 31/100, ll = -245952.04
EM iteration 32/100, ll = -199427.71
 EM iteration 32/100, ll =  -46524.11
 EM iteration 32/100, ll = -245951.82
EM iteration 33/100, ll = -199427.64
 EM iteration 33/100, ll =  -46523.98
 EM iteration 33/100, ll = -245951.62
EM iteration 34/100, ll = -199427.58
 EM iteration 34/100, ll =  -46523.87
 EM iteration 34/100, ll = -245951.46
EM iteration 35/100, ll = -199427.53
 EM iteration 35/100, ll =  -46523.78
 EM iteration 35/100, ll = -245951.32
EM iteration 36/100, ll = -199427.49
 EM iteration 36/100, ll =  -46523.70
 EM iteration 36/100, ll = -245951.19
EM iteration 37/100, ll = -199427.45
 EM iteration 37/100, ll =  -46523.63
 EM iteration 37/100, ll = -245951.09
EM iteration 38/100, ll = -199427.42
 EM iteration 38/100, ll =  -46523.58
 EM iteration 38/100, ll = -245951.00
EM iteration 39/100, ll = -199427.39
 EM iteration 39/100, ll =  -46523.53
 EM iteration 39/100, ll = -245950.92
EM iteration 40/100, ll = -199427.37
 EM iteration 40/100, ll =  -46523.48
 EM iteration 40/100, ll = -245950.85
EM iteration 41/100, ll = -199427.35
 EM iteration 41/100, ll =  -46523.45
 EM iteration 41/100, ll = -245950.80
EM iteration 42/100, ll = -199427.33
 EM iteration 42/100, ll =  -46523.41
 EM iteration 42/100, ll = -245950.75
EM iteration 43/100, ll = -199427.32
 EM iteration 43/100, ll =  -46523.39
 EM iteration 43/100, ll = -245950.71
EM iteration 44/100, ll = -199427.31
 EM iteration 44/100, ll =  -46523.36
 EM iteration 44/100, ll = -245950.67
EM iteration 45/100, ll = -199427.29
 EM iteration 45/100, ll =  -46523.34
 EM iteration 45/100, ll = -245950.64
EM iteration 46/100, ll = -199427.29
 EM iteration 46/100, ll =  -46523.33
 EM iteration 46/100, ll = -245950.61
EM iteration 47/100, ll = -199427.28
 EM iteration 47/100, ll =  -46523.31
 EM iteration 47/100, ll = -245950.59
EM iteration 48/100, ll = -199427.27
 EM iteration 48/100, ll =  -46523.30
 EM iteration 48/100, ll = -245950.57
EM iteration 49/100, ll = -199427.26
 EM iteration 49/100, ll =  -46523.29
 EM iteration 49/100, ll = -245950.55
EM iteration 50/100, ll = -199427.26
 EM iteration 50/100, ll =  -46523.28
 EM iteration 50/100, ll = -245950.54
EM iteration 51/100, ll = -199427.25
 EM iteration 51/100, ll =  -46523.27
 EM iteration 51/100, ll = -245950.53
EM iteration 52/100, ll = -199427.25
 EM iteration 52/100, ll =  -46523.26
 EM iteration 52/100, ll = -245950.51
EM iteration 53/100, ll = -199427.25
 EM iteration 53/100, ll =  -46523.26
 EM iteration 53/100, ll = -245950.51
EM iteration 54/100, ll = -199427.25
 EM iteration 54/100, ll =  -46523.25
 EM iteration 54/100, ll = -245950.50
EM iteration 55/100, ll = -199427.24
 EM iteration 55/100, ll =  -46523.25
 EM iteration 55/100, ll = -245950.49
EM iteration 56/100, ll = -199427.24
 EM iteration 56/100, ll =  -46523.24
 EM iteration 56/100, ll = -245950.48
EM iteration 57/100, ll = -199427.24
 EM iteration 57/100, ll =  -46523.24
 EM iteration 57/100, ll = -245950.48
EM iteration 58/100, ll = -199427.24
 EM iteration 58/100, ll =  -46523.24
 EM iteration 58/100, ll = -245950.48
EM iteration 59/100, ll = -199427.24
 EM iteration 59/100, ll =  -46523.24
 EM iteration 59/100, ll = -245950.47
EM iteration 60/100, ll = -199427.23
 EM iteration 60/100, ll =  -46523.23
 EM iteration 60/100, ll = -245950.47
EM iteration 61/100, ll = -199427.23
 EM iteration 61/100, ll =  -46523.23
 EM iteration 61/100, ll = -245950.47
EM iteration 62/100, ll = -199427.23
 EM iteration 62/100, ll =  -46523.23
 EM iteration 62/100, ll = -245950.46
EM iteration 63/100, ll = -199427.23
 EM iteration 63/100, ll =  -46523.23
 EM iteration 63/100, ll = -245950.46
EM iteration 64/100, ll = -199427.23
 EM iteration 64/100, ll =  -46523.23
 EM iteration 64/100, ll = -245950.46
EM iteration 65/100, ll = -199427.23
 EM iteration 65/100, ll =  -46523.23
 EM iteration 65/100, ll = -245950.46
EM iteration 66/100, ll = -199427.23
 EM iteration 66/100, ll =  -46523.23
 EM iteration 66/100, ll = -245950.46
EM iteration 67/100, ll = -199427.23
 EM iteration 67/100, ll =  -46523.23
 EM iteration 67/100, ll = -245950.46
EM iteration 68/100, ll = -199427.23
 EM iteration 68/100, ll =  -46523.22
 EM iteration 68/100, ll = -245950.45
EM iteration 69/100, ll = -199427.23
 EM iteration 69/100, ll =  -46523.22
 EM iteration 69/100, ll = -245950.45
EM iteration 70/100, ll = -199427.23
 EM iteration 70/100, ll =  -46523.22
 EM iteration 70/100, ll = -245950.45
EM iteration 71/100, ll = -199427.23
 EM iteration 71/100, ll =  -46523.22
 EM iteration 71/100, ll = -245950.45
EM iteration 72/100, ll = -199427.23
 EM iteration 72/100, ll =  -46523.22
 EM iteration 72/100, ll = -245950.45
EM iteration 73/100, ll = -199427.23
 EM iteration 73/100, ll =  -46523.22
 EM iteration 73/100, ll = -245950.45
EM iteration 74/100, ll = -199427.23
 EM iteration 74/100, ll =  -46523.22
 EM iteration 74/100, ll = -245950.45
EM iteration 75/100, ll = -199427.23
 EM iteration 75/100, ll =  -46523.22
 EM iteration 75/100, ll = -245950.45
EM iteration 76/100, ll = -199427.23
 EM iteration 76/100, ll =  -46523.22
 EM iteration 76/100, ll = -245950.45
EM iteration 77/100, ll = -199427.23
 EM iteration 77/100, ll =  -46523.22
 EM iteration 77/100, ll = -245950.45
EM iteration 78/100, ll = -199427.23
 EM iteration 78/100, ll =  -46523.22
 EM iteration 78/100, ll = -245950.45
EM iteration 79/100, ll = -199427.23
 EM iteration 79/100, ll =  -46523.22
 EM iteration 79/100, ll = -245950.45
EM iteration 80/100, ll = -199427.23
 EM iteration 80/100, ll =  -46523.22
 EM iteration 80/100, ll = -245950.45
EM iteration 81/100, ll = -199427.23
 EM iteration 81/100, ll =  -46523.22
 EM iteration 81/100, ll = -245950.45
EM iteration 82/100, ll = -199427.23
 EM iteration 82/100, ll =  -46523.22
 EM iteration 82/100, ll = -245950.45
EM iteration 83/100, ll = -199427.23
 EM iteration 83/100, ll =  -46523.22
 EM iteration 83/100, ll = -245950.45
EM iteration 84/100, ll = -199427.23
 EM iteration 84/100, ll =  -46523.22
 EM iteration 84/100, ll = -245950.45
EM iteration 85/100, ll = -199427.23
 EM iteration 85/100, ll =  -46523.22
 EM iteration 85/100, ll = -245950.45
EM iteration 86/100, ll = -199427.23
 EM iteration 86/100, ll =  -46523.22
 EM iteration 86/100, ll = -245950.45
EM iteration 87/100, ll = -199427.23
 EM iteration 87/100, ll =  -46523.22
 EM iteration 87/100, ll = -245950.45
EM iteration 88/100, ll = -199427.23
 EM iteration 88/100, ll =  -46523.22
 EM iteration 88/100, ll = -245950.45
EM iteration 89/100, ll = -199427.23
 EM iteration 89/100, ll =  -46523.22
 EM iteration 89/100, ll = -245950.45
EM iteration 90/100, ll = -199427.23
 EM iteration 90/100, ll =  -46523.22
 EM iteration 90/100, ll = -245950.45
EM iteration 91/100, ll = -199427.23
 EM iteration 91/100, ll =  -46523.22
 EM iteration 91/100, ll = -245950.45
EM iteration 92/100, ll = -199427.23
 EM iteration 92/100, ll =  -46523.22
 EM iteration 92/100, ll = -245950.45
EM iteration 93/100, ll = -199427.23
 EM iteration 93/100, ll =  -46523.22
 EM iteration 93/100, ll = -245950.45
EM iteration 94/100, ll = -199427.23
 EM iteration 94/100, ll =  -46523.22
 EM iteration 94/100, ll = -245950.45
EM iteration 95/100, ll = -199427.23
 EM iteration 95/100, ll =  -46523.22
 EM iteration 95/100, ll = -245950.45
EM iteration 96/100, ll = -199427.23
 EM iteration 96/100, ll =  -46523.22
 EM iteration 96/100, ll = -245950.45
EM iteration 97/100, ll = -199427.23
 EM iteration 97/100, ll =  -46523.22
 EM iteration 97/100, ll = -245950.45
EM iteration 98/100, ll = -199427.23
 EM iteration 98/100, ll =  -46523.22
 EM iteration 98/100, ll = -245950.45
EM iteration 99/100, ll = -199427.23
 EM iteration 99/100, ll =  -46523.22
 EM iteration 99/100, ll = -245950.45
EM iteration 100/100, ll = -199427.23
 EM iteration 100/100, ll =  -46523.22
 EM iteration 100/100, ll = -245950.45
## Estimation finished, create final object</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod_clogis &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(formula, <span class="dt">data =</span> data, <span class="dt">family =</span> <span class="st">"logistic"</span>,
                      <span class="dt">left =</span> <span class="dv">0</span>, <span class="dt">tol =</span> <span class="op">-</span><span class="ot">Inf</span>, <span class="dt">maxit =</span> <span class="dv">20</span>)</code></pre></div>
<pre><code>## Calling foehnix.unreg.fit</code></pre>
<pre><code>## Warning in iwls_logit(logitX, z, standardize = FALSE, maxit = tail(maxit, :
## IWLS solver for logistic model did not converge.

## Warning in iwls_logit(logitX, z, standardize = FALSE, maxit = tail(maxit, :
## IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 1/20, ll = -200457.45
 EM iteration 1/20, ll =  -52280.16
 EM iteration 1/20, ll = -252737.61</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 2/20, ll = -201717.12
 EM iteration 2/20, ll =  -50474.88
 EM iteration 2/20, ll = -252192.00</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 3/20, ll = -202327.77
 EM iteration 3/20, ll =  -49342.20
 EM iteration 3/20, ll = -251669.97</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 4/20, ll = -202620.76
 EM iteration 4/20, ll =  -48621.30
 EM iteration 4/20, ll = -251242.05</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 5/20, ll = -202746.25
 EM iteration 5/20, ll =  -48154.74
 EM iteration 5/20, ll = -250900.99</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 6/20, ll = -202779.38
 EM iteration 6/20, ll =  -47846.70
 EM iteration 6/20, ll = -250626.09</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 7/20, ll = -202761.69
 EM iteration 7/20, ll =  -47638.48
 EM iteration 7/20, ll = -250400.17</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 8/20, ll = -202717.42
 EM iteration 8/20, ll =  -47493.82
 EM iteration 8/20, ll = -250211.24</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 9/20, ll = -202660.94
 EM iteration 9/20, ll =  -47390.16
 EM iteration 9/20, ll = -250051.11</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 10/20, ll = -202600.69
 EM iteration 10/20, ll =  -47313.42
 EM iteration 10/20, ll = -249914.11</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 11/20, ll = -202541.44
 EM iteration 11/20, ll =  -47254.72
 EM iteration 11/20, ll = -249796.16</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 12/20, ll = -202485.74
 EM iteration 12/20, ll =  -47208.44
 EM iteration 12/20, ll = -249694.17</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 13/20, ll = -202434.78
 EM iteration 13/20, ll =  -47170.98
 EM iteration 13/20, ll = -249605.75</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 14/20, ll = -202388.96
 EM iteration 14/20, ll =  -47140.01
 EM iteration 14/20, ll = -249528.97</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 15/20, ll = -202348.22
 EM iteration 15/20, ll =  -47113.98
 EM iteration 15/20, ll = -249462.21</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 16/20, ll = -202312.28
 EM iteration 16/20, ll =  -47091.85
 EM iteration 16/20, ll = -249404.13</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 17/20, ll = -202280.73
 EM iteration 17/20, ll =  -47072.85
 EM iteration 17/20, ll = -249353.58</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 18/20, ll = -202253.13
 EM iteration 18/20, ll =  -47056.45
 EM iteration 18/20, ll = -249309.59</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 19/20, ll = -202229.04
 EM iteration 19/20, ll =  -47042.24
 EM iteration 19/20, ll = -249271.28</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 20/20, ll = -202208.04
 EM iteration 20/20, ll =  -47029.90
 EM iteration 20/20, ll = -249237.94
## Estimation finished, create final object</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mod_tlogis &lt;-<span class="st"> </span><span class="kw"><a href="../reference/foehnix.html">foehnix</a></span>(formula, <span class="dt">data =</span> data, <span class="dt">family =</span> <span class="st">"logistic"</span>,
                      <span class="dt">left =</span> <span class="dv">0</span>, <span class="dt">tol =</span> <span class="op">-</span><span class="ot">Inf</span>, <span class="dt">maxit =</span> <span class="dv">20</span>, <span class="dt">truncated =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## Calling foehnix.unreg.fit</code></pre>
<pre><code>## Warning in iwls_logit(logitX, z, standardize = FALSE, maxit = tail(maxit, :
## IWLS solver for logistic model did not converge.

## Warning in iwls_logit(logitX, z, standardize = FALSE, maxit = tail(maxit, :
## IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 1/20, ll = -196881.92
 EM iteration 1/20, ll =  -51278.44
 EM iteration 1/20, ll = -248160.36</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 2/20, ll = -198979.48
 EM iteration 2/20, ll =  -48788.41
 EM iteration 2/20, ll = -247767.89</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 3/20, ll = -200355.58
 EM iteration 3/20, ll =  -46985.00
 EM iteration 3/20, ll = -247340.58</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 4/20, ll = -201330.04
 EM iteration 4/20, ll =  -45649.26
 EM iteration 4/20, ll = -246979.30</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 5/20, ll = -202066.70
 EM iteration 5/20, ll =  -44639.25
 EM iteration 5/20, ll = -246705.95</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 6/20, ll = -202650.49
 EM iteration 6/20, ll =  -43859.17
 EM iteration 6/20, ll = -246509.66</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 7/20, ll = -203129.63
 EM iteration 7/20, ll =  -43243.76
 EM iteration 7/20, ll = -246373.40</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 8/20, ll = -203533.74
 EM iteration 8/20, ll =  -42748.00
 EM iteration 8/20, ll = -246281.74</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 9/20, ll = -203882.21
 EM iteration 9/20, ll =  -42340.34
 EM iteration 9/20, ll = -246222.55</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 10/20, ll = -204188.30
 EM iteration 10/20, ll =  -41998.41
 EM iteration 10/20, ll = -246186.71</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 11/20, ll = -204461.37
 EM iteration 11/20, ll =  -41706.10
 EM iteration 11/20, ll = -246167.47</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 12/20, ll = -204705.98
 EM iteration 12/20, ll =  -41453.02
 EM iteration 12/20, ll = -246159.00</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 13/20, ll = -204931.08
 EM iteration 13/20, ll =  -41228.74
 EM iteration 13/20, ll = -246159.83</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 14/20, ll = -205138.53
 EM iteration 14/20, ll =  -41027.30
 EM iteration 14/20, ll = -246165.84</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 15/20, ll = -205331.12
 EM iteration 15/20, ll =  -40843.91
 EM iteration 15/20, ll = -246175.04</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 16/20, ll = -205511.46
 EM iteration 16/20, ll =  -40675.07
 EM iteration 16/20, ll = -246186.53</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 17/20, ll = -205680.43
 EM iteration 17/20, ll =  -40518.08
 EM iteration 17/20, ll = -246198.51</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 18/20, ll = -205839.09
 EM iteration 18/20, ll =  -40371.02
 EM iteration 18/20, ll = -246210.11</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 19/20, ll = -205989.06
 EM iteration 19/20, ll =  -40232.52
 EM iteration 19/20, ll = -246221.57</code></pre>
<pre><code>## Warning in iwls_logit(logitX, post, beta = ccmodel$beta, standardize =
## FALSE, : IWLS solver for logistic model did not converge.</code></pre>
<pre><code>## EM iteration 20/20, ll = -206131.04
 EM iteration 20/20, ll =  -40101.21
 EM iteration 20/20, ll = -246232.25
## Estimation finished, create final object</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Information criteria</span>
get_IC &lt;-<span class="st"> </span><span class="cf">function</span>(x) <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dt">N =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(x<span class="op">$</span>filter_obj<span class="op">$</span>good), <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/logLik">logLik</a></span>(x), <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/AIC">AIC</a></span>(x), <span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/AIC">BIC</a></span>(x), <span class="kw"><a href="../reference/IGN.html">IGN</a></span>(x))
IC     &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">sapply</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="st">"gaussian"</span>           =<span class="st"> </span>mod_gauss,
                      <span class="st">"gaussian censored"</span>  =<span class="st"> </span>mod_cgauss,
                      <span class="st">"gaussian truncated"</span> =<span class="st"> </span>mod_tgauss,
                      <span class="st">"logistic"</span>           =<span class="st"> </span>mod_logis,
                      <span class="st">"logistic censored"</span>  =<span class="st"> </span>mod_clogis,
                      <span class="st">"logistic truncated"</span> =<span class="st"> </span>mod_tlogis),
                 get_IC)
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/t">t</a></span>(IC)</code></pre></div>
<pre><code>##                         N    loglik      AIC      BIC      IGN
## gaussian           102918 -246274.4 492560.8 492618.1 2.392919
## gaussian censored  102918 -247830.5 495672.9 495730.2 2.408038
## gaussian truncated 102918 -246474.3 492960.6 493017.9 2.394861
## logistic           102918 -245950.4 491912.9 491970.1 2.389771
## logistic censored  102918 -249237.9 498487.9 498545.1 2.421714
## logistic truncated 102918 -246232.2 492476.5 492533.7 2.392509</code></pre>
<p>As the number of observations the classification is based on is the same for all models, we can directly compare the information criteria (i.e., AIC, BIC, log-likelihood). In all cases the “logistic” model seems to perform best among these models.</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#data-set-description">Data Set Description</a></li>
      <li><a href="#loading-the-data-set">Loading the Data Set</a></li>
      <li><a href="#estimate-classification-model">Estimate Classification Model</a></li>
      <li><a href="#estimated-coefficients">Estimated Coefficients</a></li>
      <li><a href="#graphical-model-assessment">Graphical Model Assessment</a></li>
      <li><a href="#time-series-plot">Time Series Plot</a></li>
      <li><a href="#wind-rose-plot">Wind Rose Plot</a></li>
      <li><a href="#hovmoler-diagram">Hovmöler Diagram</a></li>
      <li><a href="#compare-models-gaussian">Compare Models (Gaussian)</a></li>
      <li><a href="#compare-models-distributions">Compare Models (Distributions)</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Reto Stauffer.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
